/** Built-in shell command candidates with i18n description keys (docker-like help). */

export type ShellCommandCatalogItem = {
  name: string
  /** vue-i18n key under shellSuggest.cmd.* */
  descKey: string
  /** Optional example / common flags shown as secondary line */
  example?: string
}

/**
 * Common interactive-shell commands. Descriptions live in i18n (zh-CN).
 * Keep names lowercase; matching is case-insensitive.
 */
export const SHELL_COMMAND_CATALOG: ShellCommandCatalogItem[] = [
  { name: 'ls', descKey: 'shellSuggest.cmd.ls', example: 'ls -lah' },
  { name: 'cd', descKey: 'shellSuggest.cmd.cd', example: 'cd /var/log' },
  { name: 'pwd', descKey: 'shellSuggest.cmd.pwd' },
  { name: 'cat', descKey: 'shellSuggest.cmd.cat', example: 'cat file.txt' },
  { name: 'less', descKey: 'shellSuggest.cmd.less' },
  { name: 'more', descKey: 'shellSuggest.cmd.more' },
  { name: 'head', descKey: 'shellSuggest.cmd.head', example: 'head -n 20 f' },
  { name: 'tail', descKey: 'shellSuggest.cmd.tail', example: 'tail -f log' },
  { name: 'cp', descKey: 'shellSuggest.cmd.cp', example: 'cp -a src dst' },
  { name: 'mv', descKey: 'shellSuggest.cmd.mv' },
  { name: 'rm', descKey: 'shellSuggest.cmd.rm', example: 'rm -rf path' },
  { name: 'mkdir', descKey: 'shellSuggest.cmd.mkdir', example: 'mkdir -p a/b' },
  { name: 'rmdir', descKey: 'shellSuggest.cmd.rmdir' },
  { name: 'touch', descKey: 'shellSuggest.cmd.touch' },
  { name: 'chmod', descKey: 'shellSuggest.cmd.chmod', example: 'chmod 755 f' },
  { name: 'chown', descKey: 'shellSuggest.cmd.chown' },
  { name: 'find', descKey: 'shellSuggest.cmd.find', example: 'find . -name "*.log"' },
  { name: 'grep', descKey: 'shellSuggest.cmd.grep', example: 'grep -R pattern .' },
  { name: 'rg', descKey: 'shellSuggest.cmd.rg' },
  { name: 'awk', descKey: 'shellSuggest.cmd.awk' },
  { name: 'sed', descKey: 'shellSuggest.cmd.sed' },
  { name: 'sort', descKey: 'shellSuggest.cmd.sort' },
  { name: 'uniq', descKey: 'shellSuggest.cmd.uniq' },
  { name: 'wc', descKey: 'shellSuggest.cmd.wc' },
  { name: 'cut', descKey: 'shellSuggest.cmd.cut' },
  { name: 'tr', descKey: 'shellSuggest.cmd.tr' },
  { name: 'xargs', descKey: 'shellSuggest.cmd.xargs' },
  { name: 'ps', descKey: 'shellSuggest.cmd.ps', example: 'ps aux' },
  { name: 'top', descKey: 'shellSuggest.cmd.top' },
  { name: 'htop', descKey: 'shellSuggest.cmd.htop' },
  { name: 'kill', descKey: 'shellSuggest.cmd.kill', example: 'kill -9 pid' },
  { name: 'killall', descKey: 'shellSuggest.cmd.killall' },
  { name: 'pkill', descKey: 'shellSuggest.cmd.pkill' },
  { name: 'df', descKey: 'shellSuggest.cmd.df', example: 'df -h' },
  { name: 'du', descKey: 'shellSuggest.cmd.du', example: 'du -sh *' },
  { name: 'free', descKey: 'shellSuggest.cmd.free', example: 'free -h' },
  { name: 'uptime', descKey: 'shellSuggest.cmd.uptime' },
  { name: 'uname', descKey: 'shellSuggest.cmd.uname', example: 'uname -a' },
  { name: 'whoami', descKey: 'shellSuggest.cmd.whoami' },
  { name: 'id', descKey: 'shellSuggest.cmd.id' },
  { name: 'which', descKey: 'shellSuggest.cmd.which' },
  { name: 'whereis', descKey: 'shellSuggest.cmd.whereis' },
  { name: 'type', descKey: 'shellSuggest.cmd.type' },
  { name: 'echo', descKey: 'shellSuggest.cmd.echo' },
  { name: 'printf', descKey: 'shellSuggest.cmd.printf' },
  { name: 'export', descKey: 'shellSuggest.cmd.export' },
  { name: 'env', descKey: 'shellSuggest.cmd.env' },
  { name: 'history', descKey: 'shellSuggest.cmd.history' },
  { name: 'clear', descKey: 'shellSuggest.cmd.clear' },
  { name: 'reset', descKey: 'shellSuggest.cmd.reset' },
  { name: 'man', descKey: 'shellSuggest.cmd.man' },
  { name: 'info', descKey: 'shellSuggest.cmd.info' },
  { name: 'ssh', descKey: 'shellSuggest.cmd.ssh' },
  { name: 'scp', descKey: 'shellSuggest.cmd.scp' },
  { name: 'rsync', descKey: 'shellSuggest.cmd.rsync' },
  { name: 'curl', descKey: 'shellSuggest.cmd.curl' },
  { name: 'wget', descKey: 'shellSuggest.cmd.wget' },
  { name: 'ping', descKey: 'shellSuggest.cmd.ping' },
  { name: 'traceroute', descKey: 'shellSuggest.cmd.traceroute' },
  { name: 'netstat', descKey: 'shellSuggest.cmd.netstat' },
  { name: 'ss', descKey: 'shellSuggest.cmd.ss', example: 'ss -lntp' },
  { name: 'ip', descKey: 'shellSuggest.cmd.ip', example: 'ip a' },
  { name: 'ifconfig', descKey: 'shellSuggest.cmd.ifconfig' },
  { name: 'tar', descKey: 'shellSuggest.cmd.tar', example: 'tar -czf a.tgz dir' },
  { name: 'zip', descKey: 'shellSuggest.cmd.zip' },
  { name: 'unzip', descKey: 'shellSuggest.cmd.unzip' },
  { name: 'gzip', descKey: 'shellSuggest.cmd.gzip' },
  { name: 'gunzip', descKey: 'shellSuggest.cmd.gunzip' },
  { name: 'systemctl', descKey: 'shellSuggest.cmd.systemctl', example: 'systemctl status nginx' },
  { name: 'service', descKey: 'shellSuggest.cmd.service' },
  { name: 'journalctl', descKey: 'shellSuggest.cmd.journalctl', example: 'journalctl -u nginx -f' },
  { name: 'dmesg', descKey: 'shellSuggest.cmd.dmesg' },
  { name: 'docker', descKey: 'shellSuggest.cmd.docker', example: 'docker ps -a' },
  { name: 'podman', descKey: 'shellSuggest.cmd.podman' },
  { name: 'kubectl', descKey: 'shellSuggest.cmd.kubectl' },
  { name: 'git', descKey: 'shellSuggest.cmd.git' },
  { name: 'npm', descKey: 'shellSuggest.cmd.npm' },
  { name: 'node', descKey: 'shellSuggest.cmd.node' },
  { name: 'python', descKey: 'shellSuggest.cmd.python' },
  { name: 'python3', descKey: 'shellSuggest.cmd.python3' },
  { name: 'pip', descKey: 'shellSuggest.cmd.pip' },
  { name: 'pip3', descKey: 'shellSuggest.cmd.pip3' },
  { name: 'apt', descKey: 'shellSuggest.cmd.apt' },
  { name: 'apt-get', descKey: 'shellSuggest.cmd.aptGet' },
  { name: 'yum', descKey: 'shellSuggest.cmd.yum' },
  { name: 'dnf', descKey: 'shellSuggest.cmd.dnf' },
  { name: 'sudo', descKey: 'shellSuggest.cmd.sudo' },
  { name: 'su', descKey: 'shellSuggest.cmd.su' },
  { name: 'vim', descKey: 'shellSuggest.cmd.vim' },
  { name: 'vi', descKey: 'shellSuggest.cmd.vi' },
  { name: 'nano', descKey: 'shellSuggest.cmd.nano' },
  { name: 'tmux', descKey: 'shellSuggest.cmd.tmux' },
  { name: 'screen', descKey: 'shellSuggest.cmd.screen' },
  { name: 'watch', descKey: 'shellSuggest.cmd.watch' },
  { name: 'tee', descKey: 'shellSuggest.cmd.tee' },
  { name: 'ln', descKey: 'shellSuggest.cmd.ln', example: 'ln -s target link' },
  { name: 'stat', descKey: 'shellSuggest.cmd.stat' },
  { name: 'file', descKey: 'shellSuggest.cmd.file' },
  { name: 'diff', descKey: 'shellSuggest.cmd.diff' },
  { name: 'lsof', descKey: 'shellSuggest.cmd.lsof' },
  { name: 'crontab', descKey: 'shellSuggest.cmd.crontab' },
]
